projects/03_helloword/06/app/models.py
from contextlib import contextmanager
from . import db


@contextmanager
def db_session_manager(session_close=True):
    """Creates a context manager to use to interact
    with the database session and assure closing
    the session at the end of the scope
    Yields:
        Session: The database session object to use
    """
    try:
        yield db.session
    except:
        db.session.rollback()
        raise
    finally:
        if session_close:
            db.session.close()


class Content(db.Model):
    """This class maps the content database table to this
    Content class, as well as defining the database table
    structure
    Args:
        db (db.Model): The database instance created when the app was created
    """

    __tablename__ = "content"
    content_id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    image_filename = db.Column(db.String)
    text = db.Column(db.String)

projects/03_helloword/06/app/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


# create an empty db instance
db = SQLAlchemy()


def create_app():
    """Initialize the flask app instance"""
    # create the flask app instance
    app = Flask(__name__)

    basedir = os.path.abspath(os.path.dirname(__file__))

    # configure information for the db
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///" + os.path.join(
        basedir, "app.db"
    )
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

    with app.app_context():
        # initialize the db instance
        db.init_app(app)

        # import the routes
        from . import home
        from . import content

        # create the database if it doesn't already exist
        db.create_all()

        # register the blueprints
        app.register_blueprint(home.home_bp)
        app.register_blueprint(content.content_bp)

        return app

projects/03_helloword/06/app/content/__init__.py
from flask import Blueprint

content_bp = Blueprint(
    "content_bp",
    __name__,
    static_folder="static",
    static_url_path="/content/static",
    template_folder="templates",
)

from app.content import views

projects/03_helloword/06/app/content/views.py
from flask import render_template
from . import content_bp
from ..models import db_session_manager, Content


@content_bp.get("/content")
def content():
    with db_session_manager() as db_session:
        data = db_session.query(Content).order_by(Content.content_id).all()
    return render_template("content.html", data=data)

projects/03_helloword/06/app/home/__init__.py
from flask import Blueprint

home_bp = Blueprint(
    "home_bp",
    __name__,
    static_folder="static",
    static_url_path="/home/static",
    template_folder="templates",
)

from app.home import views

projects/03_helloword/06/app/home/views.py
from flask import render_template
from . import home_bp


@home_bp.get("/")
def home():
    return render_template("home.html")

projects/03_helloword/06/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Freelancer - Start Bootstrap Theme</title>
    <!-- Favicon-->
    <link
      rel="icon"
      type="image/x-icon"
      href="{{url_for('static', filename='assets/favicon.ico')}}"
    />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
      crossorigin="anonymous"
    ></script>

    {% block styles %}
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link
      href="{{url_for('static', filename='css/styles.css')}}"
      rel="stylesheet"
    />
    {% endblock %}
  </head>
  <body id="page-top">
    <!-- Navigation-->
    <nav
      class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top"
      id="mainNav"
    >
      <div class="container">
        <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
        <button
          class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item mx-0 mx-lg-1">
              <a
                class="nav-link py-3 px-0 px-lg-3 rounded"
                href="{{url_for('home_bp.home') + '#portfolio'}}"
                >Portfolio</a
              >
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a
                class="nav-link py-3 px-0 px-lg-3 rounded"
                href="{{url_for('content_bp.content')}}"
                >Content</a
              >
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a
                class="nav-link py-3 px-0 px-lg-3 rounded"
                href="{{url_for('home_bp.home') + '#about'}}"
                >About</a
              >
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a
                class="nav-link py-3 px-0 px-lg-3 rounded"
                href="{{url_for('home_bp.home') + '#contact'}}"
                >Contact</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Masthead-->
    <header class="masthead bg-primary text-white text-center">
      <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img
          class="masthead-avatar mb-5"
          src="{{url_for('static', filename='assets/img/avataaars.svg')}}"
          alt="..."
        />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Start Bootstrap</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
          <div class="divider-custom-line"></div>
          <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
          <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0">
          Graphic Artist - Web Designer - Illustrator
        </p>
      </div>
    </header>
    {% block content %}{% endblock %}
    <!-- Footer-->
    <footer class="footer text-center">
      <div class="container">
        <div class="row">
          <!-- Footer Location-->
          <div class="col-lg-4 mb-5 mb-lg-0">
            <h4 class="text-uppercase mb-4">Location</h4>
            <p class="lead mb-0">
              2215 John Daniel Drive
              <br />
              Clark, MO 65243
            </p>
          </div>
          <!-- Footer Social Icons-->
          <div class="col-lg-4 mb-5 mb-lg-0">
            <h4 class="text-uppercase mb-4">Around the Web</h4>
            <a class="btn btn-outline-light btn-social mx-1" href="#!"
              ><i class="fab fa-fw fa-facebook-f"></i
            ></a>
            <a class="btn btn-outline-light btn-social mx-1" href="#!"
              ><i class="fab fa-fw fa-twitter"></i
            ></a>
            <a class="btn btn-outline-light btn-social mx-1" href="#!"
              ><i class="fab fa-fw fa-linkedin-in"></i
            ></a>
            <a class="btn btn-outline-light btn-social mx-1" href="#!"
              ><i class="fab fa-fw fa-dribbble"></i
            ></a>
          </div>
          <!-- Footer About Text-->
          <div class="col-lg-4">
            <h4 class="text-uppercase mb-4">About Freelancer</h4>
            <p class="lead mb-0">
              Freelance is a free to use, MIT licensed Bootstrap theme created
              by
              <a href="http://startbootstrap.com">Start Bootstrap</a>
              .
            </p>
          </div>
        </div>
      </div>
    </footer>
    <!-- Copyright Section-->
    <div class="copyright py-4 text-center text-white">
      <div class="container">
        <small>Copyright &copy; Your Website 2021</small>
      </div>
    </div>
    <!-- Portfolio Modals-->

    {% block scripts %}
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{{url_for('static', filename='js/scripts.js')}}"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    {% endblock %}
  </body>
</html>

projects/03_helloword/06/app/templates/macros.jinja
<!-- Portfolio Modal-->
{% macro portfolio_item(id, image_filename) %}
<div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#{{ id }}">
    <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
        <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
    </div>
    <img class="img-fluid" src="{{url_for('static', filename='assets/img/portfolio/' + image_filename)}}" alt="..." />
</div>
{% endmacro %}

{% macro portfolio_modal(id, title, image_filename, content) %}
<div class="portfolio-modal modal fade" id="{{ id }}" tabindex="-1" aria-labelledby="portfolioModal1" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header border-0"><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div>
            <div class="modal-body text-center pb-5">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <!-- Portfolio Modal - Title-->
                            <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">{{ title }}</h2>
                            <!-- Icon Divider-->
                            <div class="divider-custom">
                                <div class="divider-custom-line"></div>
                                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                                <div class="divider-custom-line"></div>
                            </div>
                            <!-- Portfolio Modal - Image-->
                            <img class="img-fluid rounded mb-5" src="{{url_for('static', filename='assets/img/portfolio/' + image_filename)}}" alt="..." />
                            <!-- Portfolio Modal - Text-->
                            <p class="mb-4">{{ content }}</p>
                            <button class="btn btn-primary" href="#!" data-bs-dismiss="modal">
                                <i class="fas fa-times fa-fw"></i>
                                Close Window
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endmacro %}